// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: bill.proto

package pb_gen

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BillStatus int32

const (
	BillStatus_Bill_Unknown   BillStatus = 0
	BillStatus_Bill_WaitToPay BillStatus = 1
	BillStatus_Bill_Paid      BillStatus = 2
)

// Enum value maps for BillStatus.
var (
	BillStatus_name = map[int32]string{
		0: "Bill_Unknown",
		1: "Bill_WaitToPay",
		2: "Bill_Paid",
	}
	BillStatus_value = map[string]int32{
		"Bill_Unknown":   0,
		"Bill_WaitToPay": 1,
		"Bill_Paid":      2,
	}
)

func (x BillStatus) Enum() *BillStatus {
	p := new(BillStatus)
	*p = x
	return p
}

func (x BillStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BillStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bill_proto_enumTypes[0].Descriptor()
}

func (BillStatus) Type() protoreflect.EnumType {
	return &file_bill_proto_enumTypes[0]
}

func (x BillStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BillStatus.Descriptor instead.
func (BillStatus) EnumDescriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{0}
}

type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   int64      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParkId   int64      `protobuf:"varint,3,opt,name=park_id,json=parkId,proto3" json:"park_id,omitempty"`
	Duration string     `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Charge   int32      `protobuf:"varint,5,opt,name=charge,proto3" json:"charge,omitempty"`
	Status   BillStatus `protobuf:"varint,6,opt,name=status,proto3,enum=car_port.BillStatus" json:"status,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bill) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Bill) GetParkId() int64 {
	if x != nil {
		return x.ParkId
	}
	return 0
}

func (x *Bill) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Bill) GetCharge() int32 {
	if x != nil {
		return x.Charge
	}
	return 0
}

func (x *Bill) GetStatus() BillStatus {
	if x != nil {
		return x.Status
	}
	return BillStatus_Bill_Unknown
}

type ReqGetBill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId int64 `protobuf:"varint,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
}

func (x *ReqGetBill) Reset() {
	*x = ReqGetBill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bill_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetBill) ProtoMessage() {}

func (x *ReqGetBill) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetBill.ProtoReflect.Descriptor instead.
func (*ReqGetBill) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetBill) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

type RespGetBill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Bill    *Bill  `protobuf:"bytes,3,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *RespGetBill) Reset() {
	*x = RespGetBill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bill_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetBill) ProtoMessage() {}

func (x *RespGetBill) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetBill.ProtoReflect.Descriptor instead.
func (*RespGetBill) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{2}
}

func (x *RespGetBill) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespGetBill) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *RespGetBill) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type ReqMGetBill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Num   int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ReqMGetBill) Reset() {
	*x = ReqMGetBill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bill_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMGetBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMGetBill) ProtoMessage() {}

func (x *ReqMGetBill) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMGetBill.ProtoReflect.Descriptor instead.
func (*ReqMGetBill) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{3}
}

func (x *ReqMGetBill) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReqMGetBill) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RespMGetBill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32   `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string  `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Bills   []*Bill `protobuf:"bytes,3,rep,name=bills,proto3" json:"bills,omitempty"`
	Count   int32   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RespMGetBill) Reset() {
	*x = RespMGetBill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bill_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespMGetBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespMGetBill) ProtoMessage() {}

func (x *RespMGetBill) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespMGetBill.ProtoReflect.Descriptor instead.
func (*RespMGetBill) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{4}
}

func (x *RespMGetBill) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespMGetBill) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *RespMGetBill) GetBills() []*Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

func (x *RespMGetBill) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_bill_proto protoreflect.FileDescriptor

var file_bill_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x61,
	0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xaa, 0x01, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x72, 0x6b, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c,
	0x6c, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x0b, 0x52, 0x65,
	0x73, 0x70, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x62,
	0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x61, 0x72, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22,
	0x35, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4d, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x7c, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x47,
	0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x62, 0x69, 0x6c, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x41, 0x0a, 0x0a, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x69, 0x6c, 0x6c, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x69, 0x6c, 0x6c, 0x5f, 0x57, 0x61, 0x69,
	0x74, 0x54, 0x6f, 0x50, 0x61, 0x79, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x69, 0x6c, 0x6c,
	0x5f, 0x50, 0x61, 0x69, 0x64, 0x10, 0x02, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x62, 0x5f,
	0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bill_proto_rawDescOnce sync.Once
	file_bill_proto_rawDescData = file_bill_proto_rawDesc
)

func file_bill_proto_rawDescGZIP() []byte {
	file_bill_proto_rawDescOnce.Do(func() {
		file_bill_proto_rawDescData = protoimpl.X.CompressGZIP(file_bill_proto_rawDescData)
	})
	return file_bill_proto_rawDescData
}

var file_bill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bill_proto_goTypes = []interface{}{
	(BillStatus)(0),      // 0: car_port.BillStatus
	(*Bill)(nil),         // 1: car_port.Bill
	(*ReqGetBill)(nil),   // 2: car_port.ReqGetBill
	(*RespGetBill)(nil),  // 3: car_port.RespGetBill
	(*ReqMGetBill)(nil),  // 4: car_port.ReqMGetBill
	(*RespMGetBill)(nil), // 5: car_port.RespMGetBill
}
var file_bill_proto_depIdxs = []int32{
	0, // 0: car_port.Bill.status:type_name -> car_port.BillStatus
	1, // 1: car_port.RespGetBill.bill:type_name -> car_port.Bill
	1, // 2: car_port.RespMGetBill.bills:type_name -> car_port.Bill
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bill_proto_init() }
func file_bill_proto_init() {
	if File_bill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bill_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetBill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bill_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespGetBill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bill_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMGetBill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bill_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespMGetBill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bill_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bill_proto_goTypes,
		DependencyIndexes: file_bill_proto_depIdxs,
		EnumInfos:         file_bill_proto_enumTypes,
		MessageInfos:      file_bill_proto_msgTypes,
	}.Build()
	File_bill_proto = out.File
	file_bill_proto_rawDesc = nil
	file_bill_proto_goTypes = nil
	file_bill_proto_depIdxs = nil
}
