// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: car_port.proto

package pb_gen

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CarPortStatus int32

const (
	CarPortStatus_Port_Unknown CarPortStatus = 0
	CarPortStatus_Port_Empty   CarPortStatus = 1
	CarPortStatus_Port_Used    CarPortStatus = 2
	CarPortStatus_Port_Abandon CarPortStatus = 3
)

// Enum value maps for CarPortStatus.
var (
	CarPortStatus_name = map[int32]string{
		0: "Port_Unknown",
		1: "Port_Empty",
		2: "Port_Used",
		3: "Port_Abandon",
	}
	CarPortStatus_value = map[string]int32{
		"Port_Unknown": 0,
		"Port_Empty":   1,
		"Port_Used":    2,
		"Port_Abandon": 3,
	}
)

func (x CarPortStatus) Enum() *CarPortStatus {
	p := new(CarPortStatus)
	*p = x
	return p
}

func (x CarPortStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CarPortStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_car_port_proto_enumTypes[0].Descriptor()
}

func (CarPortStatus) Type() protoreflect.EnumType {
	return &file_car_port_proto_enumTypes[0]
}

func (x CarPortStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CarPortStatus.Descriptor instead.
func (CarPortStatus) EnumDescriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{0}
}

type CarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   //车位id
	State     CarPortStatus `protobuf:"varint,2,opt,name=state,proto3,enum=car_port.CarPortStatus" json:"state,omitempty"` //车位状态
	Longitude float64       `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`                    //车位经度
	Latitude  float64       `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`                      //车位纬度
	Park      int64         `protobuf:"varint,5,opt,name=park,proto3" json:"park,omitempty"`                               //车位所属停车场
}

func (x *CarPort) Reset() {
	*x = CarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarPort) ProtoMessage() {}

func (x *CarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarPort.ProtoReflect.Descriptor instead.
func (*CarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{0}
}

func (x *CarPort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CarPort) GetState() CarPortStatus {
	if x != nil {
		return x.State
	}
	return CarPortStatus_Port_Unknown
}

func (x *CarPort) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CarPort) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CarPort) GetPark() int64 {
	if x != nil {
		return x.Park
	}
	return 0
}

type ReqAddCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port *CarPort `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ReqAddCarPort) Reset() {
	*x = ReqAddCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAddCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAddCarPort) ProtoMessage() {}

func (x *ReqAddCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAddCarPort.ProtoReflect.Descriptor instead.
func (*ReqAddCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{1}
}

func (x *ReqAddCarPort) GetPort() *CarPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type RespAddCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
}

func (x *RespAddCarPort) Reset() {
	*x = RespAddCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespAddCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAddCarPort) ProtoMessage() {}

func (x *RespAddCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAddCarPort.ProtoReflect.Descriptor instead.
func (*RespAddCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{2}
}

func (x *RespAddCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespAddCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

type ReqUpdateCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port *CarPort `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ReqUpdateCarPort) Reset() {
	*x = ReqUpdateCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateCarPort) ProtoMessage() {}

func (x *ReqUpdateCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateCarPort.ProtoReflect.Descriptor instead.
func (*ReqUpdateCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{3}
}

func (x *ReqUpdateCarPort) GetPort() *CarPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type RespUpdateCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
}

func (x *RespUpdateCarPort) Reset() {
	*x = RespUpdateCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUpdateCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUpdateCarPort) ProtoMessage() {}

func (x *RespUpdateCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUpdateCarPort.ProtoReflect.Descriptor instead.
func (*RespUpdateCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{4}
}

func (x *RespUpdateCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespUpdateCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

type ReqGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPortId int64 `protobuf:"varint,1,opt,name=car_port_id,json=carPortId,proto3" json:"car_port_id,omitempty"`
}

func (x *ReqGetCarPort) Reset() {
	*x = ReqGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetCarPort) ProtoMessage() {}

func (x *ReqGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetCarPort.ProtoReflect.Descriptor instead.
func (*ReqGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{5}
}

func (x *ReqGetCarPort) GetCarPortId() int64 {
	if x != nil {
		return x.CarPortId
	}
	return 0
}

type RespGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32    `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Port    *CarPort `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RespGetCarPort) Reset() {
	*x = RespGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetCarPort) ProtoMessage() {}

func (x *RespGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetCarPort.ProtoReflect.Descriptor instead.
func (*RespGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{6}
}

func (x *RespGetCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespGetCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *RespGetCarPort) GetPort() *CarPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type ReqMGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Num   int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"` //    int32 offset = 2;
}

func (x *ReqMGetCarPort) Reset() {
	*x = ReqMGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMGetCarPort) ProtoMessage() {}

func (x *ReqMGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMGetCarPort.ProtoReflect.Descriptor instead.
func (*ReqMGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{7}
}

func (x *ReqMGetCarPort) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReqMGetCarPort) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RespMGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32      `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string     `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Ports   []*CarPort `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Count   int32      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RespMGetCarPort) Reset() {
	*x = RespMGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespMGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespMGetCarPort) ProtoMessage() {}

func (x *RespMGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespMGetCarPort.ProtoReflect.Descriptor instead.
func (*RespMGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{8}
}

func (x *RespMGetCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespMGetCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *RespMGetCarPort) GetPorts() []*CarPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *RespMGetCarPort) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_car_port_proto protoreflect.FileDescriptor

var file_car_port_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x07, 0x43,
	0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x61, 0x72, 0x6b, 0x22, 0x36, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x43, 0x61,
	0x72, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x42, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x70, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x22,
	0x39, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72,
	0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x45, 0x0a, 0x11, 0x52, 0x65,
	0x73, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70,
	0x73, 0x22, 0x2f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74,
	0x49, 0x64, 0x22, 0x69, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x38, 0x0a,
	0x0e, 0x52, 0x65, 0x71, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70,
	0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x12, 0x27, 0x0a,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63,
	0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x52,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x52, 0x0a, 0x0d,
	0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a,
	0x0c, 0x50, 0x6f, 0x72, 0x74, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x6f, 0x72, 0x74, 0x5f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x50, 0x6f, 0x72, 0x74, 0x5f, 0x55, 0x73, 0x65, 0x64, 0x10, 0x02, 0x12, 0x10,
	0x0a, 0x0c, 0x50, 0x6f, 0x72, 0x74, 0x5f, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x10, 0x03,
	0x42, 0x1a, 0x5a, 0x18, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x63, 0x61, 0x72,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_car_port_proto_rawDescOnce sync.Once
	file_car_port_proto_rawDescData = file_car_port_proto_rawDesc
)

func file_car_port_proto_rawDescGZIP() []byte {
	file_car_port_proto_rawDescOnce.Do(func() {
		file_car_port_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_port_proto_rawDescData)
	})
	return file_car_port_proto_rawDescData
}

var file_car_port_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_car_port_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_car_port_proto_goTypes = []interface{}{
	(CarPortStatus)(0),        // 0: car_port.CarPortStatus
	(*CarPort)(nil),           // 1: car_port.CarPort
	(*ReqAddCarPort)(nil),     // 2: car_port.ReqAddCarPort
	(*RespAddCarPort)(nil),    // 3: car_port.RespAddCarPort
	(*ReqUpdateCarPort)(nil),  // 4: car_port.ReqUpdateCarPort
	(*RespUpdateCarPort)(nil), // 5: car_port.RespUpdateCarPort
	(*ReqGetCarPort)(nil),     // 6: car_port.ReqGetCarPort
	(*RespGetCarPort)(nil),    // 7: car_port.RespGetCarPort
	(*ReqMGetCarPort)(nil),    // 8: car_port.ReqMGetCarPort
	(*RespMGetCarPort)(nil),   // 9: car_port.RespMGetCarPort
}
var file_car_port_proto_depIdxs = []int32{
	0, // 0: car_port.CarPort.state:type_name -> car_port.CarPortStatus
	1, // 1: car_port.ReqAddCarPort.port:type_name -> car_port.CarPort
	1, // 2: car_port.ReqUpdateCarPort.port:type_name -> car_port.CarPort
	1, // 3: car_port.RespGetCarPort.port:type_name -> car_port.CarPort
	1, // 4: car_port.RespMGetCarPort.ports:type_name -> car_port.CarPort
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_car_port_proto_init() }
func file_car_port_proto_init() {
	if File_car_port_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_car_port_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAddCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespAddCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUpdateCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespUpdateCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespMGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_port_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_car_port_proto_goTypes,
		DependencyIndexes: file_car_port_proto_depIdxs,
		EnumInfos:         file_car_port_proto_enumTypes,
		MessageInfos:      file_car_port_proto_msgTypes,
	}.Build()
	File_car_port_proto = out.File
	file_car_port_proto_rawDesc = nil
	file_car_port_proto_goTypes = nil
	file_car_port_proto_depIdxs = nil
}
