// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: car_port.proto

package pb_gen

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State    int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	DrawNode int32 `protobuf:"varint,3,opt,name=draw_node,json=drawNode,proto3" json:"draw_node,omitempty"`
}

func (x *CarPort) Reset() {
	*x = CarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarPort) ProtoMessage() {}

func (x *CarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarPort.ProtoReflect.Descriptor instead.
func (*CarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{0}
}

func (x *CarPort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CarPort) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CarPort) GetDrawNode() int32 {
	if x != nil {
		return x.DrawNode
	}
	return 0
}

type ReqAddCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port *CarPort `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ReqAddCarPort) Reset() {
	*x = ReqAddCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAddCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAddCarPort) ProtoMessage() {}

func (x *ReqAddCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAddCarPort.ProtoReflect.Descriptor instead.
func (*ReqAddCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{1}
}

func (x *ReqAddCarPort) GetPort() *CarPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type RespAddCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
}

func (x *RespAddCarPort) Reset() {
	*x = RespAddCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespAddCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAddCarPort) ProtoMessage() {}

func (x *RespAddCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAddCarPort.ProtoReflect.Descriptor instead.
func (*RespAddCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{2}
}

func (x *RespAddCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespAddCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

type ReqUpdateCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port *CarPort `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ReqUpdateCarPort) Reset() {
	*x = ReqUpdateCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateCarPort) ProtoMessage() {}

func (x *ReqUpdateCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateCarPort.ProtoReflect.Descriptor instead.
func (*ReqUpdateCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{3}
}

func (x *ReqUpdateCarPort) GetPort() *CarPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type RespUpdateCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
}

func (x *RespUpdateCarPort) Reset() {
	*x = RespUpdateCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUpdateCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUpdateCarPort) ProtoMessage() {}

func (x *RespUpdateCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUpdateCarPort.ProtoReflect.Descriptor instead.
func (*RespUpdateCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{4}
}

func (x *RespUpdateCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespUpdateCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

type ReqGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarPortId int64 `protobuf:"varint,1,opt,name=car_port_id,json=carPortId,proto3" json:"car_port_id,omitempty"`
}

func (x *ReqGetCarPort) Reset() {
	*x = ReqGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetCarPort) ProtoMessage() {}

func (x *ReqGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetCarPort.ProtoReflect.Descriptor instead.
func (*ReqGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{5}
}

func (x *ReqGetCarPort) GetCarPortId() int64 {
	if x != nil {
		return x.CarPortId
	}
	return 0
}

type RespGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32    `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Port    *CarPort `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RespGetCarPort) Reset() {
	*x = RespGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetCarPort) ProtoMessage() {}

func (x *RespGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetCarPort.ProtoReflect.Descriptor instead.
func (*RespGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{6}
}

func (x *RespGetCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespGetCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *RespGetCarPort) GetPort() *CarPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type ReqMGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count  int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ReqMGetCarPort) Reset() {
	*x = ReqMGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMGetCarPort) ProtoMessage() {}

func (x *ReqMGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMGetCarPort.ProtoReflect.Descriptor instead.
func (*ReqMGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{7}
}

func (x *ReqMGetCarPort) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReqMGetCarPort) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RespMGetCarPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo      int32              `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips    string             `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Ports      map[int64]*CarPort `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NextOffset int32              `protobuf:"varint,4,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	HasMore    bool               `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *RespMGetCarPort) Reset() {
	*x = RespMGetCarPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_port_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespMGetCarPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespMGetCarPort) ProtoMessage() {}

func (x *RespMGetCarPort) ProtoReflect() protoreflect.Message {
	mi := &file_car_port_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespMGetCarPort.ProtoReflect.Descriptor instead.
func (*RespMGetCarPort) Descriptor() ([]byte, []int) {
	return file_car_port_proto_rawDescGZIP(), []int{8}
}

func (x *RespMGetCarPort) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *RespMGetCarPort) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *RespMGetCarPort) GetPorts() map[int64]*CarPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *RespMGetCarPort) GetNextOffset() int32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *RespMGetCarPort) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_car_port_proto protoreflect.FileDescriptor

var file_car_port_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x07, 0x43,
	0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x72, 0x61, 0x77, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x64, 0x72, 0x61, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x52, 0x65, 0x71,
	0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0x42, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x41, 0x64, 0x64, 0x43,
	0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x45, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x22, 0x2f, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0b, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x22, 0x6c,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74,
	0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69,
	0x70, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43,
	0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3e, 0x0a, 0x0e,
	0x52, 0x65, 0x71, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x8e, 0x02, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74,
	0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69,
	0x70, 0x73, 0x12, 0x3d, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x2e,
	0x50, 0x6f, 0x72, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x1a, 0x4e, 0x0a,
	0x0a, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x50, 0x6f,
	0x72, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xa9, 0x03,
	0x0a, 0x0e, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x61, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a,
	0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71,
	0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x41, 0x64, 0x64,
	0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22,
	0x0f, 0x2f, 0x63, 0x61, 0x72, 0x2f, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74,
	0x3a, 0x01, 0x2a, 0x12, 0x6d, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x63, 0x61,
	0x72, 0x2f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x3a,
	0x01, 0x2a, 0x12, 0x5e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52,
	0x65, 0x71, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x1a, 0x1b, 0x2e, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x11, 0x12, 0x0f, 0x2f, 0x63, 0x61, 0x72, 0x2f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x65, 0x0a, 0x0b, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x1b, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x71, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x1a, 0x1c,
	0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x1b, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x63, 0x61, 0x72, 0x2f, 0x4d, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70,
	0x62, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_car_port_proto_rawDescOnce sync.Once
	file_car_port_proto_rawDescData = file_car_port_proto_rawDesc
)

func file_car_port_proto_rawDescGZIP() []byte {
	file_car_port_proto_rawDescOnce.Do(func() {
		file_car_port_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_port_proto_rawDescData)
	})
	return file_car_port_proto_rawDescData
}

var file_car_port_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_car_port_proto_goTypes = []interface{}{
	(*CarPort)(nil),           // 0: simple_test.CarPort
	(*ReqAddCarPort)(nil),     // 1: simple_test.ReqAddCarPort
	(*RespAddCarPort)(nil),    // 2: simple_test.RespAddCarPort
	(*ReqUpdateCarPort)(nil),  // 3: simple_test.ReqUpdateCarPort
	(*RespUpdateCarPort)(nil), // 4: simple_test.RespUpdateCarPort
	(*ReqGetCarPort)(nil),     // 5: simple_test.ReqGetCarPort
	(*RespGetCarPort)(nil),    // 6: simple_test.RespGetCarPort
	(*ReqMGetCarPort)(nil),    // 7: simple_test.ReqMGetCarPort
	(*RespMGetCarPort)(nil),   // 8: simple_test.RespMGetCarPort
	nil,                       // 9: simple_test.RespMGetCarPort.PortsEntry
}
var file_car_port_proto_depIdxs = []int32{
	0, // 0: simple_test.ReqAddCarPort.port:type_name -> simple_test.CarPort
	0, // 1: simple_test.ReqUpdateCarPort.port:type_name -> simple_test.CarPort
	0, // 2: simple_test.RespGetCarPort.port:type_name -> simple_test.CarPort
	9, // 3: simple_test.RespMGetCarPort.ports:type_name -> simple_test.RespMGetCarPort.PortsEntry
	0, // 4: simple_test.RespMGetCarPort.PortsEntry.value:type_name -> simple_test.CarPort
	1, // 5: simple_test.CarPortService.AddCarPort:input_type -> simple_test.ReqAddCarPort
	3, // 6: simple_test.CarPortService.UpdateCarPort:input_type -> simple_test.ReqUpdateCarPort
	5, // 7: simple_test.CarPortService.GetCarPort:input_type -> simple_test.ReqGetCarPort
	7, // 8: simple_test.CarPortService.MGetCarPort:input_type -> simple_test.ReqMGetCarPort
	2, // 9: simple_test.CarPortService.AddCarPort:output_type -> simple_test.RespAddCarPort
	4, // 10: simple_test.CarPortService.UpdateCarPort:output_type -> simple_test.RespUpdateCarPort
	6, // 11: simple_test.CarPortService.GetCarPort:output_type -> simple_test.RespGetCarPort
	8, // 12: simple_test.CarPortService.MGetCarPort:output_type -> simple_test.RespMGetCarPort
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_car_port_proto_init() }
func file_car_port_proto_init() {
	if File_car_port_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_car_port_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAddCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespAddCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUpdateCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespUpdateCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_port_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespMGetCarPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_port_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_car_port_proto_goTypes,
		DependencyIndexes: file_car_port_proto_depIdxs,
		MessageInfos:      file_car_port_proto_msgTypes,
	}.Build()
	File_car_port_proto = out.File
	file_car_port_proto_rawDesc = nil
	file_car_port_proto_goTypes = nil
	file_car_port_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CarPortServiceClient is the client API for CarPortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarPortServiceClient interface {
	AddCarPort(ctx context.Context, in *ReqAddCarPort, opts ...grpc.CallOption) (*RespAddCarPort, error)
	UpdateCarPort(ctx context.Context, in *ReqUpdateCarPort, opts ...grpc.CallOption) (*RespUpdateCarPort, error)
	GetCarPort(ctx context.Context, in *ReqGetCarPort, opts ...grpc.CallOption) (*RespGetCarPort, error)
	MGetCarPort(ctx context.Context, in *ReqMGetCarPort, opts ...grpc.CallOption) (*RespMGetCarPort, error)
}

type carPortServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarPortServiceClient(cc grpc.ClientConnInterface) CarPortServiceClient {
	return &carPortServiceClient{cc}
}

func (c *carPortServiceClient) AddCarPort(ctx context.Context, in *ReqAddCarPort, opts ...grpc.CallOption) (*RespAddCarPort, error) {
	out := new(RespAddCarPort)
	err := c.cc.Invoke(ctx, "/simple_test.CarPortService/AddCarPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carPortServiceClient) UpdateCarPort(ctx context.Context, in *ReqUpdateCarPort, opts ...grpc.CallOption) (*RespUpdateCarPort, error) {
	out := new(RespUpdateCarPort)
	err := c.cc.Invoke(ctx, "/simple_test.CarPortService/UpdateCarPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carPortServiceClient) GetCarPort(ctx context.Context, in *ReqGetCarPort, opts ...grpc.CallOption) (*RespGetCarPort, error) {
	out := new(RespGetCarPort)
	err := c.cc.Invoke(ctx, "/simple_test.CarPortService/GetCarPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carPortServiceClient) MGetCarPort(ctx context.Context, in *ReqMGetCarPort, opts ...grpc.CallOption) (*RespMGetCarPort, error) {
	out := new(RespMGetCarPort)
	err := c.cc.Invoke(ctx, "/simple_test.CarPortService/MGetCarPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarPortServiceServer is the server API for CarPortService service.
type CarPortServiceServer interface {
	AddCarPort(context.Context, *ReqAddCarPort) (*RespAddCarPort, error)
	UpdateCarPort(context.Context, *ReqUpdateCarPort) (*RespUpdateCarPort, error)
	GetCarPort(context.Context, *ReqGetCarPort) (*RespGetCarPort, error)
	MGetCarPort(context.Context, *ReqMGetCarPort) (*RespMGetCarPort, error)
}

// UnimplementedCarPortServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCarPortServiceServer struct {
}

func (*UnimplementedCarPortServiceServer) AddCarPort(context.Context, *ReqAddCarPort) (*RespAddCarPort, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarPort not implemented")
}
func (*UnimplementedCarPortServiceServer) UpdateCarPort(context.Context, *ReqUpdateCarPort) (*RespUpdateCarPort, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCarPort not implemented")
}
func (*UnimplementedCarPortServiceServer) GetCarPort(context.Context, *ReqGetCarPort) (*RespGetCarPort, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarPort not implemented")
}
func (*UnimplementedCarPortServiceServer) MGetCarPort(context.Context, *ReqMGetCarPort) (*RespMGetCarPort, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MGetCarPort not implemented")
}

func RegisterCarPortServiceServer(s *grpc.Server, srv CarPortServiceServer) {
	s.RegisterService(&_CarPortService_serviceDesc, srv)
}

func _CarPortService_AddCarPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAddCarPort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPortServiceServer).AddCarPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple_test.CarPortService/AddCarPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPortServiceServer).AddCarPort(ctx, req.(*ReqAddCarPort))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarPortService_UpdateCarPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUpdateCarPort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPortServiceServer).UpdateCarPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple_test.CarPortService/UpdateCarPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPortServiceServer).UpdateCarPort(ctx, req.(*ReqUpdateCarPort))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarPortService_GetCarPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetCarPort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPortServiceServer).GetCarPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple_test.CarPortService/GetCarPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPortServiceServer).GetCarPort(ctx, req.(*ReqGetCarPort))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarPortService_MGetCarPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMGetCarPort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPortServiceServer).MGetCarPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple_test.CarPortService/MGetCarPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPortServiceServer).MGetCarPort(ctx, req.(*ReqMGetCarPort))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarPortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simple_test.CarPortService",
	HandlerType: (*CarPortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCarPort",
			Handler:    _CarPortService_AddCarPort_Handler,
		},
		{
			MethodName: "UpdateCarPort",
			Handler:    _CarPortService_UpdateCarPort_Handler,
		},
		{
			MethodName: "GetCarPort",
			Handler:    _CarPortService_GetCarPort_Handler,
		},
		{
			MethodName: "MGetCarPort",
			Handler:    _CarPortService_MGetCarPort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car_port.proto",
}
